sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: hxg571156946
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-secret: VLRdDtd4IdL0KdJnnDHzVNQPkIb98e
    access-key-id: LTAI5tSQHQjHdp9ZY1heenSt
    bucket-name: sky-take-out-studytest
  redis:
    host: localhost
    port: 6379
    password: hxg571156946
    database: 0